### ISSUE TITLE
Removal of `redo_until_no_change`

### ISSUE THREAD

**Issue by erikkessler1** [xinminlabs/synvert-core-ruby#282]
I have some scripts that use `redo_until_no_change`, but it looks like that was removed in the latest patch version. What was the reason for the removal and is there a recommended alternative?

**Comment by flyerhzm** [comment]
@erikkessler1 I didn't use it anymore when I writing synvert snippets, e.g. https://github.com/xinminlabs/synvert-snippets-ruby/commit/02549edc
Do you have any scenario to use this DSL?

**Comment by erikkessler1** [comment]
I was using `redo_until_no_change` to do a multi-pass approach to gather class information similar to the snippet you linked. However, I found workaround of using multiple `within_files` blocks to get that multi-pass behavior, so I think I'm good to close this. Thank you for the reply and context!
